#!/bin/sh
alias ls='ls --color=auto'
alias l='exa -l'
alias wiki2html='find . -iname "*.md" -type f -exec sh -c '"'"'pandoc "${0}" -d wiki.yaml --mathjax -o "${0%.md}.html" '"'"' {} \;'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias wreboot='sudo grub-reboot 2 && sudo reboot' # Fast reboot to Windows 10
alias vim='nvim'
